version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - order-service-net

  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: order_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_PASSWORD: root1234
    networks:
      - order-service-net

  order-service-app:
    container_name: order-service-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      SPRING_PROFILES_ACTIVE: dev
      SPRING_RABBITMQ_HOST: rabbitmq  # Add this line to specify RabbitMQ host
      SPRING_RABBITMQ_PORT: 5672
    networks:
      - order-service-net


networks:
  order-service-net: